apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: ellamma-ecommerce
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ellamma-ecommerce
  labels:
    project: ecommerce-project
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: ecommerce-project
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: ecommerce-project
        component: mysql
        tier: db
    spec:
      serviceAccountName: secret-mysql-reader
      initContainers:
      - name: fetch-secret
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value --secret-id roboshop/dev/mysql_password --query 'SecretString'	--output text | jq -r '.["mysqlpassword"]'
        volumeMounts:
        - name: mysql-secret
          mountPath: /tmp
      containers:
      - name: mysql
        image: shankarntr/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql-config
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 20
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: mysql-secret
          mountPath: /tmp
      volumes:
          - name: mysql-config
            configMap:
              name: mysql-config
          - name: mysql-secret
            emptyDir: {}